# src/train.py
import torch
import torch.optim as optim
import torch.nn as nn
import os
from tqdm import tqdm # For progress bar

# Use relative imports within the src package
from src import config
from src.tokenizer_utils import train_or_load_tokenizer
from src.model import create_model
from src.data_utils import create_dataloader

def train():
    print(f"Using device: {config.DEVICE}")

    # --- 1. Load Tokenizer ---
    tokenizer = train_or_load_tokenizer()
    pad_token_id = tokenizer.token_to_id(config.PAD_TOKEN)
    if pad_token_id is None:
         raise ValueError("PAD token ID not found after loading tokenizer.")


    # --- 2. Create Model ---
    model = create_model(tokenizer)
    model.to(config.DEVICE)

    # --- 3. Create DataLoader ---
    train_dataloader = create_dataloader(tokenizer)

    # --- 4. Setup Optimizer and Loss ---
    optimizer = optim.AdamW(model.parameters(), lr=config.LEARNING_RATE)
    # Use ignore_index for padding in labels (set to -100 in collate_fn)
    criterion = nn.CrossEntropyLoss(ignore_index=-100)

    # --- 5. Training Loop ---
    print("Starting training...")
    if not os.path.exists(config.OUTPUT_DIR):
        os.makedirs(config.OUTPUT_DIR)

    total_batches = len(train_dataloader)

    for epoch in range(config.NUM_EPOCHS):
        print(f"\n--- Starting Epoch {epoch+1}/{config.NUM_EPOCHS} ---")
        model.train() # Set model to training mode
        epoch_loss = 0.0
        batch_progress = tqdm(train_dataloader, desc=f"Epoch {epoch+1}", total=total_batches)

        for i, batch in enumerate(batch_progress):
            # Move batch to device
            input_ids = batch['input_ids'].to(config.DEVICE)
            labels = batch['labels'].to(config.DEVICE)
            # Get the attention mask generated by collate_fn
            attention_mask = batch['attention_mask'].to(config.DEVICE)


            # Forward pass
            optimizer.zero_grad()
            # Pass the key_padding_mask to the model's forward method
            logits = model(input_ids, src_padding_mask=attention_mask) # Pass padding mask here

            # Calculate loss
            # Reshape logits: [batch_size * seq_len, vocab_size]
            # Reshape labels: [batch_size * seq_len]
            loss = criterion(logits.view(-1, tokenizer.get_vocab_size()), labels.view(-1))

            # Backward pass and optimization
            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0) # Gradient clipping
            optimizer.step()

            current_loss = loss.item()
            epoch_loss += current_loss

            # Update progress bar
            if (i + 1) % config.LOG_INTERVAL == 0:
                 avg_loss_interval = epoch_loss / (i + 1) # Avg loss so far in epoch
                 batch_progress.set_postfix({'loss': f"{current_loss:.4f}", 'avg_loss': f"{avg_loss_interval:.4f}"})


            # Save Checkpoint
            if (i + 1) % config.SAVE_INTERVAL == 0:
                 ckpt_path = os.path.join(config.OUTPUT_DIR, f"model_epoch_{epoch+1}_batch_{i+1}.pt")
                 torch.save({
                     'epoch': epoch + 1,
                     'batch': i + 1,
                     'model_state_dict': model.state_dict(),
                     'optimizer_state_dict': optimizer.state_dict(),
                     'loss': current_loss,
                     # Include config/tokenizer info if needed for reloading
                     'vocab_size': tokenizer.get_vocab_size(),
                     'model_config': {
                         'd_model': config.D_MODEL, 'nhead': config.N_HEADS,
                         'num_layers': config.N_LAYERS, 'dim_feedforward': config.D_FF,
                         'max_seq_len': config.MAX_SEQ_LEN, 'dropout': config.DROPOUT
                         }
                 }, ckpt_path)
                 print(f"\nCheckpoint saved to {ckpt_path}")


        avg_epoch_loss = epoch_loss / total_batches
        print(f"--- Epoch {epoch+1} Finished --- Average Loss: {avg_epoch_loss:.4f}")

        # Save model at the end of each epoch
        epoch_save_path = os.path.join(config.OUTPUT_DIR, f"model_epoch_{epoch+1}_final.pt")
        # Save only the state dict for final epoch model usually
        torch.save(model.state_dict(), epoch_save_path)
        print(f"Model saved after epoch {epoch+1} to {epoch_save_path}")

    # --- 6. Final Save ---
    final_model_path = os.path.join(config.OUTPUT_DIR, "final_model.pt")
    torch.save(model.state_dict(), final_model_path)
    print(f"Final model state dict saved to {final_model_path}")

    print("Training finished!")

if __name__ == "__main__":
    train()